const guests = [
    "*Adam Groner",
    "*Elise Levin-Guracar",
    "*Sharon Levin",
    "*Ismayil Guracar",
    "*Sasha Levin-Guracar",
    "*Joe Shutz",
    "*Susan Groner",
    "*Daniel Groner",
    "*Rebecca Groner",
    "*Stefanie  Waldorf",
    "*Sam Waldorf",
    "*Noreen Ohcana",
    "*David Ohcana",
    "*Noa Ohcana",
    "*Maya Ohcana",
    "*Michele Madansky",
    "*Travis Mowbray",
    "*Harris Mowbray",
    "*Ezra Mowbray",
    "*Cynthia Madansky",
    "*Paula Madansky",
    "*Michael Groner",
    "*Elizabeth Groner",
    "Marcia Groner",
    "*Gen Guracar",
    "*Osman Guracar",
    "*Danielle Correa",
    "*Evren Guracar",
    "*Brad Hirschfield",
    "*Rebecca Hirschfield",
    "*Becky Hirschfield",
    "*Avi Hirschfield",
    "*Dini Hirschfield",
    "*Hadassah Cohen",
    "*Dassi Cohen",
    "*Brian Cohen",
    "*Debbie Haizman",
    "*Paul Haizman",
    "*Ari Klawans",
    "*Gabriel Klawans",
    "*Elijah Klawans",
    "*Jonathan Klawans",
    "*Helaine NEEDED",
    "*Mayer Steibel",
    "Zach Porges",
    "Alyssa Braver",
    "Ryan Kass",
    "Aly Vanderwalde",
    "Kaityn Kwan",
    "Eric Morris",
    "Rony Krell",
    "Lisa Fierstein",
    "Dan Greener",
    "Hannah Isakowitz",
    "Ethan Joseph",
    "Harris Karsh",
    "Manasi Raje",
    "Adam Hackel ",
    "Larry Rosenzweig",
    "Michelle Chipetine",
    "Reid Cohen",
    "Olivia and Erik",
    "Lisa Burtzlaff",
    "Chelsea Mitchell",
    "Cari Vallo",
    "Malik Vallo",
    "Barbara Stroud",
    "Kimbal Stroud",
    "Patricia Stroud",
    "Abhineet Ram",
    "Aaron Litt",
    "Molly Ludlow",
    "Sarina Gross",
    "Bethany Landrum",
    "Robert Leland",
    "Donna Leland",
    "Taner Aksu",
    "Josse De Lenner",
    "Jean Forstner",
    "Matson Wade",
    "Mayan Moses",
    "Janel Moses",
    "Asher Moses",
    "Jane Woodman",
    "Marion Pavillet",
    "Julia Dagum",
    "Naa Evans",
    "Teresa Lara-Meloy",
    "Paula Leland",
    "Ken Rafanan",
    "Natalie Seer",
    "Bao Nguyen",
    "Brian Powers",
    "Eileen Chan",
    "Paul Martin",
    "Erin Smith",
    "Mike Kuliga",
    "Naomi Leiserson",
    "Ellen Arad",
    "Graham Arad",
    "Ellen Gross",
    "Marc Gross",
    "Robin Bronk",
    "Richard Schechtman",
    "Mark Medin",
    "Lisa Medin",
    "Karen Ergas",
    "Sandy Farago"
];

export const isInvited = (name?: string): boolean => {
    return !!name && (guests.includes(name) || guests.includes(`*${name}`));
}

export const showFridayInvite = (name?: string): boolean => {
    return guests.includes(`*${name}`);
}
